language: node_js
node_js:
  - "8"

script:
  - yarn run build

cache:
  yarn: true

deploy:
  - provider: npm
    email: "iteam4u@ya.ru"
    api_token: $NPM_KEY
    api_key: $NPM_KEY
    cleanup: true
    tag: next
    edge: true
    on:
      all_branches: true
      branch: dev
      repo: midrock/vue-mapp