language: node_js
node_js:
  - "8"

script:
  - yarn run build

cache:
  yarn: true

deploy:
  - provider: npm
    email: "iteam4u@ya.ru"
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      branch: dev
      repo: midrock/vue-mapp
      tags: true
